### PR TITLE
added streamlit app

### PR DESCRIPTION
**Pull request by shashankdeshpande**
Following points are covered in this PR:
- Added Streamlit app. (CTF,FTC,ATP,PTA)
- Fixed bug in PTA style transfer

@PrithivirajDamodaran Attaching screenshot of streamlit app for reference. Let me know your suggestions

app_screenshot

### CODE REVIEW

**Comment by PrithivirajDamodaran** [comment]
Please don't mix up concerns - let this be a PR for the streamlit app alone. Will review that. Thanks

**Comment by shashankdeshpande** [comment]
Thanks @PrithivirajDamodaran 
I have made relevant changes. You can now review streamlit app.

**Comment by PrithivirajDamodaran** [comment]
@shashankdeshpande - The confidence score on the left bar is wrong and misguiding. You might want to bring these 3 knobs on the left bar with some sensible defaults. inference_on=0, quality_filter=0.95, max_candidates=5. Values given are the sensible defaults.

**Comment by shashankdeshpande** [comment]
@PrithivirajDamodaran I have added knobs in left sidebar with default values as suggested.
app_screenshot_knobs

**Comment by PrithivirajDamodaran** [comment]
@shashankdeshpande Looks great ! 

Two things: 

1. can we add a header with a sub header stating the GitHub link ? so just in case a screenshot floats around people would know for which library front end is for. 

2. You have steamlit hosting account or we just add a section to readme with instructions to run the demo ?

**Comment by shashankdeshpande** [comment]
@PrithivirajDamodaran 
- I have added header and sub-header with GitHub link
- Tried hosting this app on [streamlit](https://share.streamlit.io/) but failing due to [resource limits](https://docs.streamlit.io/en/stable/deploy_streamlit_app.html#resource-limits). Can proceed with section in readme.

**Pull request merged**
